language: node_js
node_js:
- '8.4'

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.1.0
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn run test

after_success:
  - yarn global add firebase-tools
  - yarn run deploy:submit.vefverdlaun.is
